### ISSUE TITLE
Get last image returns an error for monochrome images

### ISSUE THREAD

**Issue by rtortori** [rennmaus-coder/ninaAPI#1]
Apparently, /api/get/equipment?property=image doesn't work with monochrome images.
I assume we always try to debayer the image?

`
{'Result': {'Response': '', 'Error': 'Unsupported CFA/Bayer pattern: Monochrome', 'Success': False, 'Type': 'API'}, 'Id': 2469512, 'Exception': None, 'Status': 5, 'IsCanceled': False, 'IsCompleted': True, 'CreationOptions': 0, 'AsyncState': None, 'IsFaulted': False}
`

**Comment by rennmaus-coder** [comment]
I will have a look, thanks for reporting!

**Comment by rennmaus-coder** [comment]
fixed in new version, tested with monochrome simulator
