### ISSUE TITLE
Invalid JSON?

### ISSUE THREAD

**Issue by JuergenTerpe** [rennmaus-coder/ninaAPI#4]
I'm trying to use your cool N.I.N.A. API. ImageHistory works fine, but you did a lot more of work, so why not use everything which is supported? So I started requesting all the connected hardware to show it as a first step. The camera works, but the mount (telescope) gives me an invalid JSON file. I used QuickType.io to convert the returned JSON into a swift struct, but this and many other online tools report an invalid JSON. 

I think the issue is in the strings "DecString" and "RAString", which include another " for the arc seconds. I don't see any additional use for these elements, but maybe you want to fix this. 

Best regards,
Jürgen

Here is the returned JSON: 

{
  "Response": {
    "CanPark": true,
    "CanSetPierSide": true,
    "Coordinates": {
      "RA": 22.486304798217034,
      "RAString": "22:29:11",
      "RADegrees": 337.29457197325553,
      "Dec": 39.15701729910714,
      "DecString": "39° 09' 25"","Epoch":0,"DateTime":{"Now":"2024-05-29T18: 41: 14.3239054+02: 00","UtcNow":"2024-05-29T16: 41: 14.3240837Z","MinValue":"0001-01-01T00: 00: 00","MaxValue":"9999-12-31T23: 59: 59.9999999"}},"CanSetDeclinationRate":true,"AtPark":true,"DeviceId":"ASCOM.GS.Sky.Telescope","TimeToMeridianFlipString":"24: 00: 00","CanSetPark":true,"SiteLongitude":12.009722222222,"AtHome":false,"SiteElevation":200,"UTCDate":"2024-05-29T16: 41: 13.567","AltitudeString":"00° 47' 59"",
      "DriverInfo": null,
      "TrackingEnabled": false,
      "Azimuth": 354.36081970618295,
      "DisplayName": "ASCOM GS Sky Telescope",
      "SiteLatitude": 51.4194444444,
      "Declination": 39.15701729910714,
      "DeclinationString": "39° 09' 25"","TargetCoordinates":null,"EquatorialSystem":0,"TrackingModes":[0,3,1,2,4,5],"SecondaryAxisRates":[{"Item1":0,"Item2":3.5}],"SiderealTimeString":"10: 00: 04","Altitude":0.7997970108118071,"SupportedActions":["Telescope: SetParkPosition"],"AzimuthString":"354° 21' 39"",
      "HoursToMeridianString": "24:00:00",
      "CanMovePrimaryAxis": true,
      "CanMoveSecondaryAxis": true,
      "SideOfPier": 0,
      "PrimaryAxisRates": [
        {
          "Item1": 0,
          "Item2": 3.5
        }
      ],
      "AlignmentMode": 2,
      "CanPulseGuide": true,
      "CanFindHome": true,
      "TargetSideOfPier": null,
      "SiderealTime": 10.001000704988837,
      "GuideRateDeclinationArcsecPerSec": 7.520533589349999,
      "HasUnknownEpoch": false,
      "TimeToMeridianFlip": 24,
      "CanSetTrackingEnabled": true,
      "CanSetRightAscensionRate": true,
      "RightAscensionString": "22:29:11",
      "RightAscension": 22.486304798217034,
      "DriverVersion": null,
      "Slewing": false,
      "Description": null,
      "CanSlew": true,
      "IsPulseGuiding": true,
      "TrackingRate": {
        "TrackingMode": 5,
        "CustomRightAscensionRate": null,
        "CustomDeclinationRate": null
      },
      "Connected": true,
      "GuideRateRightAscensionArcsecPerSec": 7.520533589349999,
      "Name": "ASCOM GS Sky Telescope"
    },
    "Error": "",
    "Success": true,
    "Type": "API"
  }
}

**Comment by rennmaus-coder** [comment]
This is strange and definitely shouldn't happen, I will take a look. Thanks!

**Comment by JuergenTerpe** [comment]
Sorry, my fault. There must be a bug in the JSON beautifier plugin on Safari "eating" the "\". In raw format it looks okay, so I will reformat it manually and retry reading it via JSONDecoder. I will inform you if I get this working.

**Comment by JuergenTerpe** [comment]
Yes, this JSON beautifier is a bad thing! Sorry!
